### ISSUE TITLE
DriveNames Error

### ISSUE THREAD

**Issue by mirrorclone** [anime-republic/Mirror-New#5]
2021-09-06T03:56:27.085043+00:00 app[worker.1]: Traceback (most recent call last):
2021-09-06T03:56:27.085046+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
2021-09-06T03:56:27.085047+00:00 app[worker.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2021-09-06T03:56:27.085047+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
2021-09-06T03:56:27.085047+00:00 app[worker.1]:     return _get_module_details(pkg_main_name, error)
2021-09-06T03:56:27.085048+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-09-06T03:56:27.085049+00:00 app[worker.1]:     __import__(pkg_name)
2021-09-06T03:56:27.085049+00:00 app[worker.1]:   File "/usr/src/app/bot/__init__.py", line 534, in <module>
2021-09-06T03:56:27.085049+00:00 app[worker.1]:     DRIVES_NAMES.append(temp[0].replace("_", " "))

**Comment by anime-republic** [comment]
read wiki https://github.com/anime-republic/Mirror-New/wiki/%F0%9F%94%B4-Mandatory-Vars#search-all-drive-function

**Comment by mirrorclone** [comment]
TELEGRAMX 1h-1ssqcWD12OBIf_EtaMoJt7tu_WIO1AR https://www.live.workers.dev/1:/TELEGRAMX  Not work

**Comment by anime-republic** [comment]
TELEGRAMX 1h-1ssqcWD12OBIf_EtaMoJt7tu_WIO1AR https://www.live.workers.dev/1:


by the way that's not team drive id

**Comment by anime-republic** [comment]
if that drive is main use root

**Comment by anime-republic** [comment]
TELEGRAMX root https://www.live.workers.dev/1:

**Comment by mirrorclone** [comment]
drive folder Mandatory Vars Can you remove it ,error

ı make this 
TELEGRAMx 0APJEMkGYWKgfUk9PVA https://www.live.workers.dev/1:

2021-09-06T04:19:51.471734+00:00 app[worker.1]: Traceback (most recent call last):
2021-09-06T04:19:51.471734+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
2021-09-06T04:19:51.471735+00:00 app[worker.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2021-09-06T04:19:51.471735+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
2021-09-06T04:19:51.471735+00:00 app[worker.1]:     return _get_module_details(pkg_main_name, error)
2021-09-06T04:19:51.471736+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-09-06T04:19:51.471737+00:00 app[worker.1]:     __import__(pkg_name)
2021-09-06T04:19:51.471738+00:00 app[worker.1]:   File "/usr/src/app/bot/__init__.py", line 534, in <module>
2021-09-06T04:19:51.471738+00:00 app[worker.1]:     DRIVES_NAMES.append(temp[0].replace("_", " "))
2021-09-06T04:19:51.471739+00:00 app[worker.1]: IndexError: list index out of range

**Comment by anime-republic** [comment]
example my : Rutorrent 0AMZj_YYAEzy4Uk9PVA https://torrent.animerepublic.workers.dev/6:

you can use it or use find folder id

**Comment by mirrorclone** [comment]
ı use replit not work

![Screenshot_1](https://user-images.githubusercontent.com/86728257/132160974-84b38518-166f-45c4-99de-b198b9b787c9.png)

**Comment by anime-republic** [comment]
read screen,that ask you how many drive you want to add

**Comment by anime-republic** [comment]
it should be number

**Comment by mirrorclone** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/86728257/132161419-065538fc-8372-43d4-96ad-9d092496893d.png)


work sir thank you so much :)
