### ISSUE TITLE
Not Upload Drive Fail

### ISSUE THREAD

**Issue by mirrorclone** [anime-republic/Mirror-New#6]
2021-09-06T16:20:49.238476+00:00 app[worker.1]: Exception in thread Thread-4:
2021-09-06T16:20:49.238491+00:00 app[worker.1]: Traceback (most recent call last):
2021-09-06T16:20:49.238505+00:00 app[worker.1]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-09-06T16:20:49.238760+00:00 app[worker.1]:     self.run()
2021-09-06T16:20:49.238773+00:00 app[worker.1]:   File "/usr/lib/python3.8/threading.py", line 870, in run
2021-09-06T16:20:49.238931+00:00 app[worker.1]:     self._target(*self._args, **self._kwargs)
2021-09-06T16:20:49.238945+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/mirror.py", line 120, in onDownloadComplete
2021-09-06T16:20:49.239053+00:00 app[worker.1]:     drive.upload(up_name)
2021-09-06T16:20:49.239066+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 317, in upload
2021-09-06T16:20:49.239176+00:00 app[worker.1]:     self.__listener.onUploadComplete(link, size, files, folders, typ)
2021-09-06T16:20:49.239187+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/mirror.py", line 213, in onUploadComplete
2021-09-06T16:20:49.239315+00:00 app[worker.1]:     sendMarkup(msg + log_m + fwdpm, self.bot, self.update, InlineKeyboardMarkup([[InlineKeyboardButton(text="CLICK HERE", url=logmsg.link)]]))

**Comment by anime-republic** [comment]
can you send log at group support 😅

**Comment by mirrorclone** [comment]
ı send bro not work not open index link and drive link

**Comment by anime-republic** [comment]
fixed?

**Comment by mirrorclone** [comment]
No sir i send message telegram

6 Eyl 2021 Pzt 22:20 tarihinde anime republic ***@***.***>
şunu yazdı:

**Comment by mirrorclone** [comment]
fi
